## This file (forum_nonholonomic.sage) was *autogenerated* from the file forum_nonholonomic.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('forum_nonholonomic')
try:
 _st_.inline(0, matrix([[1, 2], [3,4]])^2)
except:
 _st_.goboom(87)
_st_.endofdoc()
