# This file was *autogenerated* from the file forum_nonholonomic.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_87 = Integer(87)## This file (forum_nonholonomic.sage) was *autogenerated* from the file forum_nonholonomic.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('forum_nonholonomic')
try:
 _st_.inline(_sage_const_0 , matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 ,_sage_const_4 ]])**_sage_const_2 )
except:
 _st_.goboom(_sage_const_87 )
_st_.endofdoc()
